.TH L1OIPCTRL 8
.SH NAME
l1oipctrl \- isdn layer 1 over IP utility
.SH SYNOPSIS
misdn_log \<port>\ \ [param]
.SH DESCRIPTION
Configures isdn layer 1 over IP setting
.SH Parameters
.B getpeer
gets current peer IP setting
.TP
.B unsetpeer
releases current peer IP
.TP
.B setpeer
\<remote host>\ \<remote port> [\<local port>]
.SH SEE ALSO
http://www.misdn.org/index.php/Misdn_log
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Joerg Dorchain <joerg@dorchain.net>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
