.TH MISDN_LOG 8
.SH NAME
misdn_log \- D/E-Channel logging utility
.SH SYNOPSIS
misdn_log \-c<n>\ \-w\ <file>
.SH DESCRIPTION
D/E-Channel logging to console and/or wireshark readably EyeSDN binary format
.SH OPTIONS
.B \-c<n>
use card number n (default 1)
.TP
.B \-w\ <file>
write wiresharkdump <file>
.SH SEE ALSO
http://www.misdn.org/index.php/Misdn_log
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Victor Seva <linuxmaniac@torreviejawireless.org>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
