.TH MISDN_CLEANL2 8
.SH NAME
misdn_cleanl2 \- cleans L2 on selected card
.SH SYNOPSIS
misdn_cleanl2 \-c<n>
.SH OPTIONS
.B \-c<n>
use card number n (default 1)
.TP
.SH SEE ALSO
http://www.misdn.org/
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Victor Seva <linuxmaniac@torreviejawireless.org>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
