.TH MISDN_RENAME 8
.SH NAME
misdn_rename \- user space utility to rename a mISDN device
.SH SYNOPSIS
misdn_rename <old name or ID> <new name>
.SH DESCRIPTION
utility to rename layer1 instance
.SH SEE ALSO
http://www.misdn.org/index.php/Misdn_rename
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Victor Seva <linuxmaniac@torreviejawireless.org>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
