.TH MISDN_INFO 8
.SH NAME
misdn_info \- list devices
.SH SYNOPSIS
misdn_info
.SH DESCRIPTION
lists all mISDN v2 devices/ports currently registered at your mISDN core
.SH SEE ALSO
http://www.misdn.org/index.php/Misdn_info
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Victor Seva <linuxmaniac@torreviejawireless.org>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
